#!/usr/bin/env python3
"""Tests for bin/transform.py, driven off test/fixtures/incoming/.

Run: python3 test/test_transform.py

Deliberately dependency-free (no pytest) so CI needs only requirements.txt. Each check
prints PASS/FAIL and the script exits non-zero if any failed.

What the review contract asks these to demonstrate rather than assert:
  * idempotency — run twice, byte-identical output, no second-run churn
  * loud failure — the broken and legacy fixtures produce actionable errors
  * ownership — hand-written files are refused, orphans are pruned
  * renderability — no entry lands in a section the site would render blank (D14)
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys
import tempfile

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
FIXTURES = REPO / "test" / "fixtures" / "incoming"
TRANSFORM = REPO / "bin" / "transform.py"

_failures: list[str] = []


def check(label: str, ok: bool, detail: str = "") -> None:
    print(f"{'PASS' if ok else 'FAIL'}  {label}")
    if not ok:
        _failures.append(f"{label}{': ' + detail if detail else ''}")
        if detail:
            print(f"      {detail}")


def transform(incoming: pathlib.Path, repo: pathlib.Path, *extra: str):
    return subprocess.run(
        [sys.executable, str(TRANSFORM), "--incoming", str(incoming), "--repo", str(repo), *extra],
        capture_output=True, text=True,
    )


_repo_seq = 0


def fresh_repo(tmp: pathlib.Path) -> pathlib.Path:
    """An empty repo root per scenario, so one test cannot inherit another's output."""
    global _repo_seq
    _repo_seq += 1
    repo = tmp / f"repo{_repo_seq}"
    (repo / "_data").mkdir(parents=True)
    return repo


def main() -> int:
    with tempfile.TemporaryDirectory() as td:
        tmp = pathlib.Path(td)

        # ---- valid fixture: transforms, and the output is what the site expects --------
        repo = fresh_repo(tmp)
        first = transform(FIXTURES / "valid", repo)
        check("valid/ transforms cleanly", first.returncode == 0, first.stderr.strip())

        cv_path, socials_path = repo / "_data" / "cv.yml", repo / "_data" / "socials.yml"
        check("writes _data/cv.yml and _data/socials.yml", cv_path.exists() and socials_path.exists())

        if cv_path.exists():
            text = cv_path.read_text()
            check("output carries the generated header",
                  text.startswith("# GENERATED by bin/transform.py"))
            doc = yaml.safe_load(text)
            check("output is wrapped in `cv:` as al_folio_cv requires", "cv" in doc)
            cv = doc.get("cv", {})
            sections = cv.get("sections", {})

            check("no `location` key (the gem accepts then silently drops it)",
                  "location" not in cv)

            # D14: custom sections must be renderable by the generic branch.
            special = {"Experience", "Education", "Projects", "Awards", "Skills",
                       "Languages", "Academic Interests"}
            bad = [
                f"{title}[{i}]"
                for title, entries in sections.items() if title not in special
                for i, e in enumerate(entries)
                if "bullet" not in e and not ("label" in e and "details" in e)
            ]
            check("custom sections use bullet/label+details only (D14)", not bad, str(bad))

            check("research interests land in `Academic Interests`, not `Research Interests`",
                  "Academic Interests" in sections and "Research Interests" not in sections)

            awards = sections.get("Awards", [])
            check("awards carry both `name` (RenderCV anchor) and `title` (gem)",
                  bool(awards) and all("name" in a and "title" in a for a in awards))

            exp = sections.get("Experience", [])
            check("ongoing entry gets end_date: present (D15)",
                  any(e.get("end_date") == "present" for e in exp))
            check("experience is reverse-chronological with ongoing first",
                  [e.get("company") for e in exp][:1] == ["Example Aerospace"],
                  str([e.get("company") for e in exp]))

            projects = sections.get("Projects", [])
            check("projects sort by importance then name",
                  [p.get("name") for p in projects]
                  == ["Example Rendezvous Simulator", "Weekend Telemetry Dashboard",
                      "An Undated Side Project"],
                  str([p.get("name") for p in projects]))

            students = sections.get("Supervised Students", [])
            check("student bullets carry the supervisor affiliation from the graph",
                  any("NOVA FCT" in s.get("bullet", "") for s in students))

        if socials_path.exists():
            socials = yaml.safe_load(socials_path.read_text())
            check("socials uses jekyll-socials' real key names",
                  socials.get("github_username") == "johndoe"
                  and socials.get("linkedin_username") == "johndoe"
                  and socials.get("orcid_id") == "0000-0002-1825-0097",
                  str(socials))
            check("a network with no built-in key becomes a {logo,title,url} mapping",
                  isinstance(socials.get("cienciavitae"), dict)
                  and "logo" in socials["cienciavitae"],
                  str(socials.get("cienciavitae")))

        # ---- dateless entries are undated, not "ongoing" (review of PR #5) -----------
            names = [p.get("name") for p in projects]
            undated = next((p for p in projects if p.get("name") == "An Undated Side Project"), {})
            check("a dateless entry is not laundered into end_date: present",
                  "end_date" not in undated and "start_date" not in undated, str(undated))
            exp_names = [e.get("position") for e in exp]
            check("a dateless entry sorts last, never above dated work",
                  exp_names and exp_names[-1] == "Undated Early Role", str(exp_names))
            undated_exp = next((e for e in exp if e.get("position") == "Undated Early Role"), {})
            check("a dateless experience carries no invented dates",
                  "end_date" not in undated_exp and "start_date" not in undated_exp,
                  str(undated_exp))

        # ---- Phase 5: personal.yml -> _data/personal.yml + _books/ -------------------
        personal_path = repo / "_data" / "personal.yml"
        check("writes _data/personal.yml", personal_path.exists())
        if personal_path.exists():
            pages = {p["slug"]: p for p in yaml.safe_load(personal_path.read_text())["pages"]}
            check("every Personal page is carried through except Reading (D17)",
                  set(pages) == {"music", "cycling_and_hiking", "diy"}, str(sorted(pages)))
            check("the _root pseudo-section leads, before the named ones",
                  pages["music"]["sections"][0]["slug"] == "_root")
            check("an ampersand slug round-trips to a readable title",
                  pages["cycling_and_hiking"]["title"] == "Cycling & Hiking")
            check("page-level profiles become links that always have a url (D19)",
                  all(l.get("url") for l in pages["cycling_and_hiking"]["links"]),
                  str(pages["cycling_and_hiking"].get("links")))
            check("an absent description is omitted rather than emitted empty",
                  "description" not in pages["diy"], str(pages["diy"].keys()))

        books = sorted((repo / "_books").glob("*.md"))
        check("one _books page per Reading entry (D17)", len(books) == 1, str(books))
        if books:
            book = books[0].read_text()
            check("front matter opens on line 1 — a marker above it would stop Jekyll "
                  "parsing it at all, silently costing the page its layout",
                  book.startswith("---\n"), book[:40])
            check("the generated marker lives inside the front matter",
                  "GENERATED by bin/transform.py" in book.split("---")[1])
            check("a partial date is padded so the shelf's `date: '%Y'` yields a year",
                  "started: '2026-07-01'" in book,
                  "unpadded, the shelf heading renders '2026-07' instead of '2026'")
            check("status is inferred from the section header when unset",
                  "status: reading" in book)

        # ---- idempotency: run twice, nothing changes ---------------------------------
        watched = [repo / "_data", repo / "_books"]
        snapshot = lambda: {  # noqa: E731
            p: p.read_bytes() for d in watched for p in sorted(d.rglob("*")) if p.is_file()
        }
        before = snapshot()
        second = transform(FIXTURES / "valid", repo)
        after = snapshot()
        check("running twice is byte-identical (P5)", before == after)
        check("second run reports up to date", "up to date" in second.stdout, second.stdout.strip())
        check("--check passes on fresh output", transform(FIXTURES / "valid", repo, "--check").returncode == 0)

        # ---- --check catches stale committed output ----------------------------------
        cv_path.write_text(cv_path.read_text().replace("Researcher", "Tinkerer"))
        stale = transform(FIXTURES / "valid", repo, "--check")
        check("--check fails on stale output (D4)", stale.returncode == 1)
        check("--check says what it would rewrite", "would rewrite" in stale.stderr, stale.stderr.strip())

        # ---- refuses to clobber a hand-written file ----------------------------------
        repo2 = fresh_repo(tmp)
        (repo2 / "_data" / "cv.yml").write_text("# hand-written, no generated header\ncv: {}\n")
        refused = transform(FIXTURES / "valid", repo2)
        check("refuses to overwrite a file without the header", refused.returncode == 1)
        check("hand-written file is left untouched",
              "hand-written" in (repo2 / "_data" / "cv.yml").read_text())

        # ---- prunes an orphan it owns, leaves foreign files alone (P6) ---------------
        repo3 = fresh_repo(tmp)
        transform(FIXTURES / "valid", repo3)
        orphan = repo3 / "_data" / "gone.yml"
        orphan.write_text("# GENERATED by bin/transform.py from _incoming/ — do not edit by hand\na: 1\n")
        foreign = repo3 / "_data" / "kept.yml"
        foreign.write_text("a: 1\n")
        pruning = transform(FIXTURES / "valid", repo3)
        check("prunes a generated file whose source is gone (P6)", not orphan.exists())
        check("leaves files it does not own", foreign.exists())
        check("reports the prune", "pruned" in pruning.stdout, pruning.stdout.strip())

        # ---- socials must not silently drop a field it cannot map --------------------
        repo_s = fresh_repo(tmp)
        staged_s = tmp / "new-network"
        shutil.copytree(FIXTURES / "valid", staged_s)
        prof = yaml.safe_load((staged_s / "profile.yml").read_text())
        prof["mastodon"] = {"id": "@someone@example.social", "url": "https://example.social/@someone"}
        (staged_s / "profile.yml").write_text(yaml.safe_dump(prof, sort_keys=False, allow_unicode=True))
        _rehash(staged_s)
        newnet = transform(staged_s, repo_s)
        check("an unmapped profile field is loud, not silently dropped",
              newnet.returncode == 1 and "mastodon" in newnet.stderr, newnet.stderr.strip()[:200])

        repo_w = fresh_repo(tmp)
        staged_w = tmp / "work-email"
        shutil.copytree(FIXTURES / "valid", staged_w)
        prof = yaml.safe_load((staged_w / "profile.yml").read_text())
        del prof["email_personal"]
        prof["email_work"] = "work@example.org"
        (staged_w / "profile.yml").write_text(yaml.safe_dump(prof, sort_keys=False, allow_unicode=True))
        _rehash(staged_w)
        transform(staged_w, repo_w)
        socials_w = yaml.safe_load((repo_w / "_data" / "socials.yml").read_text())
        check("a work-only email still produces an email link",
              socials_w.get("email") == "work@example.org", str(socials_w))

        # ---- orphaned output must not pass --check once the export is gone -----------
        repo_o = fresh_repo(tmp)
        transform(FIXTURES / "valid", repo_o)
        gone = tmp / "export-removed"
        gone.mkdir()
        (gone / "README.md").write_text("# export deleted\n")
        orphan_check = transform(gone, repo_o, "--check")
        check("--check fails when generated files outlive their export",
              orphan_check.returncode == 1 and "sourceless" in orphan_check.stderr,
              orphan_check.stderr.strip()[:200])
        orphan_run = transform(gone, repo_o)
        check("a real run prunes the sourceless files",
              orphan_run.returncode == 0 and not (repo_o / "_data" / "cv.yml").exists(),
              orphan_run.stdout.strip())

        # ---- the negative fixtures ---------------------------------------------------
        # broken/ carries schema_version 99, so the version gate fires first — deliberately,
        # since content cannot be validated against a contract version we do not know.
        repo4 = fresh_repo(tmp)
        broken = transform(FIXTURES / "broken", repo4)
        check("broken/ fails", broken.returncode == 1)
        check("broken/ fails on the version gate before touching content",
              "schema_version" in broken.stderr, broken.stderr.strip())
        check("broken/ writes nothing", not (repo4 / "_data" / "cv.yml").exists())

        # Content validation therefore needs a fixture the gate lets through: a valid v1
        # manifest with broken/cv.yml's content. This is the path that must report ALL
        # violations rather than dying on the first.
        repo4b = fresh_repo(tmp)
        staged_bad = tmp / "broken-content"
        staged_bad.mkdir()
        shutil.copy(FIXTURES / "broken" / "cv.yml", staged_bad / "cv.yml")
        _write_manifest(staged_bad, ["cv.yml", "manifest.json"])
        bad_content = transform(staged_bad, repo4b)
        check("broken content fails", bad_content.returncode == 1)
        planted = ["'position' is a required property", "September 2014", "halfway", "Chairperson"]
        missing = [p for p in planted if p not in bad_content.stderr]
        check("broken content reports every violation, not just the first", not missing,
              str(missing) + " | " + bad_content.stderr.strip()[:300])
        check("broken content writes nothing", not (repo4b / "_data" / "cv.yml").exists())

        repo5 = fresh_repo(tmp)
        legacy = transform(FIXTURES / "legacy-unversioned", repo5)
        check("legacy-unversioned/ is refused", legacy.returncode == 1)
        check("legacy failure names schema_version and the upstream issue",
              "schema_version" in legacy.stderr and "logseq-alfolio-export#1" in legacy.stderr,
              legacy.stderr.strip())

        # ---- an unmapped top-level section must be loud, not silent -------------------
        repo6 = fresh_repo(tmp)
        staged = tmp / "unmapped"
        shutil.copytree(FIXTURES / "valid", staged)
        cv_in = yaml.safe_load((staged / "cv.yml").read_text())
        cv_in["talks"] = [{"name": "A Talk"}]
        (staged / "cv.yml").write_text(yaml.safe_dump(cv_in, sort_keys=False, allow_unicode=True))
        # Keep the manifest honest so we test the section guard, not the hash check.
        _rehash(staged)
        unmapped = transform(staged, repo6)
        check("an unmapped cv.yml section is a hard error, not silent loss",
              unmapped.returncode == 1 and "talks" in unmapped.stderr, unmapped.stderr.strip())

        # ---- "not staged" vs "partially copied" --------------------------------------
        repo7 = fresh_repo(tmp)
        absent = transform(tmp / "does-not-exist", repo7)
        check("absent _incoming/ exits 0 with an explanation",
              absent.returncode == 0 and "nothing staged" in absent.stdout, absent.stdout.strip())

        readme_only = tmp / "readme-only"
        readme_only.mkdir()
        (readme_only / "README.md").write_text("# what goes here\n")
        empty = transform(readme_only, fresh_repo(tmp))
        check("a README-only _incoming/ is 'nothing staged', not an error",
              empty.returncode == 0 and "nothing staged" in empty.stdout, empty.stdout.strip())

        partial = tmp / "partial"
        partial.mkdir()
        shutil.copy(FIXTURES / "valid" / "cv.yml", partial / "cv.yml")   # no manifest.json
        half = transform(partial, fresh_repo(tmp))
        check("export files with no manifest.json is a loud partial-copy failure",
              half.returncode == 1 and "manifest.json is missing" in half.stderr,
              half.stderr.strip())

    print()
    if _failures:
        print(f"{len(_failures)} check(s) failed", file=sys.stderr)
        return 1
    print("all transform checks passed")
    return 0


def _write_manifest(staged: pathlib.Path, files: list[str]) -> None:
    """A valid contract-v1 manifest for a hand-built staged directory."""
    import hashlib, json
    hashes = {
        n: hashlib.sha256((staged / n).read_bytes()).hexdigest()
        for n in files if n != "manifest.json"
    }
    (staged / "manifest.json").write_text(json.dumps({
        "schema_version": 1,
        "exported_at": "2026-03-20T09:41:12.518Z",
        "files": files,
        "hashes": hashes,
    }, indent=2) + "\n")


def _rehash(staged: pathlib.Path) -> None:
    """Recompute manifest hashes after editing a staged fixture copy."""
    import hashlib, json
    manifest = json.loads((staged / "manifest.json").read_text())
    manifest["hashes"] = {
        name: hashlib.sha256((staged / name).read_bytes()).hexdigest()
        for name in manifest["hashes"]
    }
    (staged / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    sys.exit(main())
